preset: psr12

enabled:
  - align_double_arrow
  - length_ordered_imports
  - method_separation
  - multiline_array_trailing_comma
  - no_extra_consecutive_blank_lines
  - no_short_bool_cast
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - short_array_syntax
  - unused_use

disabled:
  - new_with_braces
  - function_declaration # TODO: Re-enable once arrow functions can be differentiated
