version: '3'

services:

  ## PHP Container ###########
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    env_file:
      - .env
    volumes:
      - ./:/var/www
    depends_on:
      - memcached
      - redis

  ## Memcached Container ###########
  memcached:
    image: memcached:1.6-alpine

  ## Redis Container ###########
  redis:
    image: redis:6.2-alpine

  pushgateway:
    image: prom/pushgateway
